# Generated by Django 5.0.6 on 2024-05-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
