# Generated by Django 5.0.6 on 2024-07-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_barprofile_name_userprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barprofile',
            old_name='bar',
            new_name='user',
        ),
    ]
