# Generated by Django 5.0.6 on 2024-05-29 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0004_rename_profile_userprofile_alter_bar_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
