# Generated by Django 5.0.6 on 2024-05-29 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_bar_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='promotionpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='barprofile',
            name='bar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bar_profile', to='userAPI.bar'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='userAPI.promotionpost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='userAPI.user'),
        ),
        migrations.AlterField(
            model_name='promotionpost',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='userAPI.bar'),
        ),
        migrations.AlterField(
            model_name='promotionpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promotionpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='promotion_likes', to='userAPI.user'),
        ),
        migrations.AlterField(
            model_name='setlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_locations', to='userAPI.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userAPI.user'),
        ),
    ]
