# Generated by Django 5.0.6 on 2024-05-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_bar_profile_picture_promotionpost_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by_set', to='userAPI.bar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='userAPI.user')),
            ],
            options={
                'unique_together': {('user', 'bar')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friended_by_set', to='userAPI.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to='userAPI.user')),
            ],
            options={
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
